### ISSUE TITLE
Create a separate graphic editor

### ISSUE THREAD

**Issue by MacIT54** [MacIT54/SigmaEdit#8]
Create a separate graphic editor window and add a toolbar containing:

1. brush with size, color, style;
2. eraser of a specified size;
3. changing the scene background;
4. adding shapes by specifying their size, fill and stroke;
5. deleting shapes.

**Comment by Mikhail-Mrikh** [comment]
im sorry dont worry

**Comment by MacIT54** [comment]
Task completed
